/*UST HESABI OLMAYAN HESAPLARI BULMAYA YARAR*/
DECLARE @CODE VARCHAR(24)
DECLARE @MCODE VARCHAR(24)
DECLARE @L INT
DECLARE @CNT INT

DECLARE EMCC CURSOR FOR
SELECT CODE FROM LG_001_EMUHACC 
WHERE LEVEL_<> 0
ORDER BY CODE
OPEN EMCC
  
FETCH NEXT FROM EMCC
INTO @CODE
 WHILE @@FETCH_STATUS = 0
  BEGIN
	SELECT @L = LEN(@CODE)
	WHILE @L >= 0
           BEGIN
                IF SUBSTRING(@CODE,@L,1)='.'
                 BEGIN 
		      SELECT @MCODE = SUBSTRING(@CODE,1,@L-1)
		      BREAK 	
		 END
                SELECT @L = @L-1				      
	   END	
        SELECT @CNT = COUNT(*) FROM LG_001_EMUHACC
	WHERE CODE = @MCODE  
	IF @CNT = 0
         SELECT @CODE	

FETCH NEXT FROM EMCC
INTO @CODE
END
CLOSE EMCC
DEALLOCATE EMCC

