DECLARE
@MuhCode varchar(25),
@LEVEL_ smallint,
@SUBACCOUNTS smallint,
@SAY  SMALLINT
DECLARE MUH_CURSOR CURSOR FOR
SELECT 
	CODE,LEVEL_
FROM 
	LG_080_EMUHACC
ORDER BY 
	CODE
OPEN MUH_CURSOR
FETCH NEXT FROM MUH_CURSOR
into @MuhCode ,@LEVEL_
WHILE @@FETCH_STATUS = 0
BEGIN
SET ROWCOUNT 0
SELECT @SAY = COUNT(*)FROM LG_080_EMUHACC WHERE CODE LIKE @MuhCode+'%' AND LEVEL_=@LEVEL_+1
UPDATE LG_080_EMUHACC SET SUBACCOUNTS=@SAY 
WHERE CODE=@MuhCode
FETCH NEXT FROM MUH_CURSOR
into @MuhCode ,@LEVEL_
END
CLOSE MUH_CURSOR
DEALLOCATE MUH_CURSOR

